### ISSUE TITLE
IEB-005: Leaves are too far from logs

### ISSUE THREAD

**Issue by faeldray** [Pyrix25633/Fabric-ImprovedEnd#10]
**Describe the bug**
The leaves on the trees in the End are too far from the logs and decay once the area is loaded, leaving quite a mess.

**To Reproduce**
Visit the End and go to the End Barrens.

**Expected behavior**
Leaves don't decay or trees are less "bushy".

**Screenshots**
<img width="282" alt="End saplings" src="https://user-images.githubusercontent.com/967709/193182987-7e74d59a-7d70-403c-a239-cde4f27fded4.png">

**Additional context**
Using version 1.0.0 on Quilt 1.18.2.

**Comment by Pyrix25633** [comment]
It will be fixed in a new version for 1.19.2, possibly on Monday 24, thank you for the report.

**Comment by faeldray** [comment]
Will there be no fix for 1.18.2 then?

**Comment by Pyrix25633** [comment]
Nope, once the mod is updated to a newer Minecraft version, older versions won't receive updates.
Fixed in upcoming 1.0.3.
