### ISSUE TITLE
IEB-006: Improper geckolib shading

### ISSUE THREAD

**Issue by Sunconure11** [Pyrix25633/Fabric-ImprovedEnd#11]
https://cdn.discordapp.com/attachments/1022207917077823569/1039234355324784750/image.png

![shading](https://user-images.githubusercontent.com/5614902/200677704-fcdcc453-25d9-4333-8b45-1cf12f310905.png)

https://gist.github.com/Sunconure11/a5050ba9d8620f34a1ecf62d37a1884e

**Comment by Sunconure11** [comment]
@AzureDoom might be able to provide more info

**Comment by Pyrix25633** [comment]
I don't know, I tried it on Quilt modloader and it worked just fine, could you tell @AzureDoom to explain the problem here? Thank you.

**Comment by Sunconure11** [comment]
Azure has stated they will be busy for a bit.

**Comment by Sunconure11** [comment]
Also, my mobo failed and I won’t have PC access for this until Tuesday

**Comment by Pyrix25633** [comment]
No problem, when you'll be able to explain the problem I'll try to fix it. Until fixed or proved invalid this issue will remain open.

**Comment by Pyrix25633** [comment]
It should work now with 1.0.4 (releasing soon), I made it an external dependency, this problem should be fixed.

**Comment by Pyrix25633** [comment]
Sorry, not releasing so soon, few things changed with 1.19.3, I'll wait KaupenJoe tutorial to see how to update some things

**Comment by Sunconure11** [comment]
Can you release a build for 1.19.2, at least? It seems some modders are refusing to go to 1.19.3 because of some changes that make them want to wait on 1.20

**Comment by Sunconure11** [comment]
Some pretty major modders, at that, too.

**Comment by Pyrix25633** [comment]
Sorry for the delay, doing it right now.

**Comment by Pyrix25633** [comment]
Released 1.19.2-1.0.4, made it an external dependency, hope it works now!
