### ISSUE TITLE
IEB-007: Fabric version is dependant on Quilt API on CurseForge

### ISSUE THREAD

**Issue by Dekamir** [Pyrix25633/Fabric-ImprovedEnd#12]
**Describe the bug**
Downloading the version 1.0.4 version of the mod in a Fabric environment causes CurseForge to download the Quilt API, even though it is not required and does not work.

**To Reproduce**
Download or update to version 1.0.4 via the CurseForge app in a Fabric profile.

**Expected behavior**
Not download the Quilt API.

**Comment by Pyrix25633** [comment]
Uhm, the fact is that the mod file is for both Fabric and Quilt, I'll just put both API's as optional, but obviously Fabric API is required for Fabric and Quilted Fabric API is for Quilt. Thank you for reporting this problem, hope it'll work better now.
