### ISSUE TITLE
IEB-001: End grass turns into dirt when an end tree grows on top of it

### ISSUE THREAD

**Issue by FluffyBumblebees** [Pyrix25633/Fabric-ImprovedEnd#3]

**Comment by Pyrix25633** [comment]
That is not true! It transforms into end stone. Please specify which end grass. improved_end:dark_grass_block to improved_end:indigo_grass_block and improved_end:xibien transforms into minecraft:end_stone..
![2022-08-18_11 34 29](https://user-images.githubusercontent.com/82797674/185363094-a7799f95-1c82-4940-bd3f-1fecb32a95c4.png)

**Comment by FluffyBumblebees** [comment]
It happens when growing a tree on it.

**Comment by FluffyBumblebees** [comment]
Automatically turning into dirt once grown

**Comment by Pyrix25633** [comment]
Uhm, ok, it will be solved for 1.0.0
