### ISSUE TITLE
IEB-005: Squids spawn randomly

### ISSUE THREAD

**Issue by faeldray** [Pyrix25633/Fabric-ImprovedEnd#9]
**Describe the bug**
Indigo squids spawn in random locations and suffocate to death.

**To Reproduce**
Visit the End and look for the squid.

**Expected behavior**
The squids spawn in water or don't suffocate on land.

**Screenshots**
![2022-09-23_12 32 29](https://user-images.githubusercontent.com/967709/193181224-9ad231ef-2f16-4f76-827b-4dfdb7e89fbd.png)

**Additional context**
Using version 1.0.0 on Quilt 1.18.2.

**Comment by Pyrix25633** [comment]
It should be fixed since 1.0.2, I'll check, thank you for the report.

**Comment by Pyrix25633** [comment]
Already solved in newer versions
